// <auto-generated />
using System;
using Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace email_signature.Server.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    [Migration("20250730112258_Initital")]
    partial class Initital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            #pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Template")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Prefix")
                        .HasColumnType("nvarchar(32)");
                    b.Property<string>("PrefixEN")
                        .HasColumnType("nvarchar(32)");
                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(256)");
                    b.Property<string>("FirstNameEN")
                        .HasColumnType("nvarchar(256)");
                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(256)");
                    b.Property<string>("LastNameEN")
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("nvarchar(32)");
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(128)");
                    b.Property<string>("TitleEN")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)");
                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(32)");
                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(32)");
                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(16)");
                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(256)");
                    b.Property<string>("DepartmentEN")
                        .HasColumnType("nvarchar(256)");
                    b.Property<string>("DepartmentLong")
                        .HasColumnType("nvarchar(256)");
                    b.Property<string>("DepartmentAbbr")
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
            #pragma warning restore 612, 618
        }
    }
}
